### ISSUE TITLE
[Bug]: Gear in Taurakamik Shrine does not turn

### ISSUE THREAD

**Issue by brentward** [MaxLastBreath/TOTK-mods#123]
### Describe the bug

```bash
In the Taurakamik Shrine near the Gerudo Canyon Stable the big gear before the shrine exit, used to ride up to get the chest does not turn. It will turn in fits and starts sometimes, but not consistently.
```

### Reproduction steps

```bash
1. Enter Taurakamik Shrine
2. Proceed to the end of the shrine before entering the exit room
3. Facing the exit there is a large gear to the left which you can reverse time on to ride up normally
4. The gear is not consistently moving
```

### Additional context

```bash
I am running in the final Yuzu version at 4k 60 fps, using optimizer presets at high and legacy settings at Balanced Nvidia, except Remove Depth of Field and remove Lens Flare are deselected.
I am running an i5 13600k with an RTX 4080.
```

### What's your operating system?

Windows 11

**Comment by MaxLastBreath** [comment]
The gear has been fixed and should be working even at 120 fps, are you sure you are not using other mods that are interfering?

**Comment by brentward** [comment]
I only have the optimizer mod and the playstation UI mod running. I will try it without the playstation UI mod and see what happens. I'm running version 1.2.0 of TotK

**Comment by brentward** [comment]
I double cheked that no other mods are installed and I even rest the cache and shaders and cleared out the mods directory and reran the optimizer without the playstation UI and I still have the issue.
I pulled up my afterburner overlay and noticed that the framerate goes up to around 100 fps when I enter the shrine even though it is locked to 60 or below outside the shrine.

**Comment by MaxLastBreath** [comment]
> I double cheked that no other mods are installed and I even rest the cache and shaders and cleared out the mods directory and reran the optimizer without the playstation UI and I still have the issue. I pulled up my afterburner overlay and noticed that the framerate goes up to around 100 fps when I enter the shrine even though it is locked to 60 or below outside the shrine.

do you have fps to uncap in Yuzu?

**Comment by brentward** [comment]
I'm not sure what you mean by this. Is this something I need to change in Yuzu or do I need to cap the framerate in Yuzu to 60 with an external tool like RTSS or the Nvidia control panel?
I was under the impression that the Yuzu settings were automatically optimized with the tool.
