### ISSUE TITLE
Ryujinx config broken after applying 

### ISSUE THREAD

**Issue by chinhodado** [MaxLastBreath/TOTK-mods#62]
After applying TOTK Optimizer, Ryujinz config is broken and it loads the default config file

TOTK Optimizer 1.5.4
Ryujinx 1.1.1101

```
00:00:00.228 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.230 |W| Application : Failed to load config! Loading the default config instead.
Failed config location C:\Users\xxx\AppData\Roaming\Ryujinx\Config.json
00:00:00.231 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1101
00:00:00.234 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.234 |N| Application Print: CPU: AMD Ryzen 5 5600X 6-Core Processor ; 12 logical
00:00:00.235 |N| Application Print: RAM: Total 31.9 GiB ; Available 19.7 GiB
00:00:00.237 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.238 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.601 |W| Application ApplyTheme: The "custom_theme_path" section in "Config.json" contains an invalid path: "Ryujinx.Common.ReactiveObject`1[System.String]".
```

**Comment by MaxLastBreath** [comment]
I realized its an issue with 1.5.4 cuz ryujinx config breaks by literally blowing air at it lol. I will fix it after the holidays :)

**Comment by MaxLastBreath** [comment]
Should be Fixed~ in [latest](https://github.com/MaxLastBreath/TOTK-mods/releases/latest)

**Comment by katosabi** [comment]
Hi there, thanks for this great tool! 

It appears this is still an issue in 1.5.5:

```00:00:00.228 |W| Application : Failed to load config! Loading the default config instead.
Failed config location C:\Users\redacted\AppData\Roaming\Ryujinx\Config.json
00:00:00.591 |W| Application ApplyTheme: The "custom_theme_path" section in "Config.json" contains an invalid path: "Ryujinx.Common.ReactiveObject`1[System.String]".
```
From what I see, it's adding quotation marks to the value for docked mode (left is after being modified by TOTK optimizer, right is native file), which Ryujinx doesn't like:

![image](https://github.com/MaxLastBreath/TOTK-mods/assets/69480402/1609ebbf-d197-4ee6-b4db-6a37a988035c)

If you remove the quotation marks, Ryujinx loads fine with the modified config.

**Comment by MaxLastBreath** [comment]
Oh... Interesting, I'll look into it again very very soon. makes sense
